### ISSUE TITLE
The "Add Pixel Dice" button on the Dice Configuration dialog throws an error.

### ISSUE THREAD

**Issue by zeel01** [foundryvtt/pixels#1]
On the `PixelsConfiguration` app, the "Add Pixel Dice" button does not function correctly. Clicking it causes `TypeError: this.object.request is not a function`.

It appears that the app expects to have been constructed with an object called `manager` but this object is not passed to the constructor when it is invoked by ` _onClickSubmenu` from the game settings application. This renders it impossible to connect dice through the UI.

I found that I can invoke `pixelsDice.PIXELS.request()` in the console as a work-around. 

Now that I have added a die, it looks like `PixelsConfiguration` gets rendered during the `ready` hook, and when this happens it is constructed with the `manager` object. But if you close the popup, and try to open it again from the settings config app, it will once again be unusable.

**Comment by nikolasbasler** [comment]
I had the same problem as well at first, and could connect the die with the command you mentioned. Strangely though, when I refreshed Chrome, the Dice Configuration window appeared and the "Add Pixel Dice" button worked. I did not have the "Use the new permissions backend for Web Bluetooth" enabled.

Pixels - Electronic Dice module 0.0.2
Foundry 10.303, running via Molten Hosting
Chrome 118.0.5993.117
