### ISSUE TITLE
Module installs 0.1.0 by default

### ISSUE THREAD

**Issue by JamzTheMan** [foundryvtt/pixels#12]
Module doesn't install 0.2.0 by default (new installs) on v12 and wants to install unfullfilled-rolls.

![image](https://github.com/user-attachments/assets/801fb02f-5ab2-4dcc-923e-a0fd7b36d1e7)

**Comment by pavalanche** [comment]
Confirmed. Had exactly same problem. Needed manual update after install to get 0.2.0
