### ISSUE TITLE
Die loses connection

### ISSUE THREAD

**Issue by nikolasbasler** [foundryvtt/pixels#2]
After connecting my die by entering ```pixelsDice.PIXELS.request()``` into the console as described in https://github.com/foundryvtt/pixels/issues/1, I could make a few rolls. But then I got this message: 
```
Lost connection to Pixel Pixel3d6bcddd, attempting to re-establish.
fetch @ foundry.js:59246
```
Unfortunately the die didn't reconnect automatically. I reconnected it using the same command and immediately got the same warning message again, but this time the re-connection seems to have worked.

I'm using the Pixels module version 0.0.2, Unfulfilled Rolls version 0.1.3, Foundry 10.303 via Molten Hosting and Chrome 118.0.5993.117

**Comment by aaclayton** [comment]
Should be fixed by version `0.1.0` although some connectivity issues may still remain due to the (occasionally) fickle nature of the web bluetooth framework.
