### ISSUE TITLE
Module not appearing in Foundry's module installer

### ISSUE THREAD

**Issue by nikolasbasler** [foundryvtt/pixels#3]
I could not find this module inside Foundry's module installer. I found a link to the mudule manifest URL posted by Atropos on the Pixels Dice Discord: ```https://github.com/foundryvtt/pixels/releases/download/0.0.1/module.json``` and then update the app to version 0.0.2 inside Foundry.

Foundry 10.303, running via Molten Hosting

**Comment by aaclayton** [comment]
Fixed now that version `0.1.0` is released the package is public.
