### ISSUE TITLE
SETUP.PackageUpdateCoreundefined

### ISSUE THREAD

**Issue by Auntben** [foundryvtt/pixels#5]
Whenever I try to update my modules, Pixels gives me a warning: SETUP.PackageUpdateCoreundefined

Module 0.1.0
Foundry Build 315

![Screenshot 2024-03-06 201859](https://github.com/foundryvtt/pixels/assets/106361199/9414fea9-3285-475d-a483-d496683a7c3c)

**Comment by briavers** [comment]
Any feedback on this please?

**Comment by nikolasbasler** [comment]
Same for me. But then again, there is no newer version than 0.1.0.

**Comment by Fyorl** [comment]
This is a core bug with that translation string. The warning should say that there is a newer version of the module available, but it requires a newer version of the core software. In this case, Pixels versions 0.2 and above require at least Foundry VTT Version 12. If you are still using Version 11 of the core software, version 0.1 is the only version of the Pixels module that is supported.
