### ISSUE TITLE
Option to only use Pixels dice for prompted rolls

### ISSUE THREAD

**Issue by nikolasbasler** [foundryvtt/pixels#6]
I wonder if it would be possible to add an option so that rolls with a Pixels are only registered if there is a (Unfulfilled Rolls?) window that is waiting for a roll (or suppress rolls that happened when there is no window, if you want to look at it this way).

This is the reason why I think this would be useful: In my group we play alot with dice cups. If someone needs to make a test, they click the appropriate button and roll their dice. This works quite well. But then they will drop the dice back into the dice cup and set it aside. This always triggers another unintended roll. I don't think this can be handled by the firmware as it's a more rigorous movement than just shifting the die to the side. 

An unprompted roll can still be done with a Pixels if triggered by a chat command (or the Dice Tray module).

**Comment by 117ksk** [comment]
I have also seen some PF2e system issue in which unintended roll or even double rolls happen. Seems to be linked to the fact that if you roll at any point, foundry will roll the die in chat immediately, even without any prompt. Promted rolls seem to work fine. A feature to disable any "off-the-cuff" rolls and only accept data from the Pixel when a roll is specifically prompted could solve or help troubleshoot various system/module conflicts etc.
